### ISSUE TITLE
Access denied error appears after clicking the Open lookup screeen button for the PickerField 

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/helium-theme-editor#13]
### Environment
Browser: Firefox 75.0 

### Description of the bug or enhancement

1. Click on the All Components
2. Scroll to the PickerFiald groupbox
3. Open lookup screen to select a related entity

A.R. `Access denied` error message occurs.
Error appears for all Pickerfield in the PickerField groupbox that have "Open lookup screen" button
![изображение](https://user-images.githubusercontent.com/24281695/78779635-4f4df180-79ae-11ea-9e60-bd6fb5104c17.png)

Also, Bug reproduce for LookupPickerField

**Comment by GlebDurygin** [comment]
It is a normal behaviour. In this application, such functionality is not provided, since the application is needed to show the appearance of the components and not their functionality.
