### ISSUE TITLE
Variables for buttons are not applied

### ISSUE THREAD

**Issue by ZhaniyaDautbekova** [cuba-platform/helium-theme-editor#26]
When configuring the buttons, I used the built-in Cuba platform styles: primary, default, danger, secondary
I configured colors according to these styles (screen 1), uploaded and added variables to the project (see screen 2, they are already filled in the demo stand)
on the 3rd screen the register button has a disabled class. Style for disabled button are not applied
![helium](https://user-images.githubusercontent.com/67406294/85667597-927f4d00-b6df-11ea-9394-395e5806212f.jpg)
![button-vars](https://user-images.githubusercontent.com/67406294/85667670-a75be080-b6df-11ea-94ed-d0acfa0f1028.jpg)
![image](https://user-images.githubusercontent.com/67406294/85667856-db370600-b6df-11ea-8654-e1214da4aaea.png)

Please check a issue.

**Comment by GlebDurygin** [comment]
Hello @ZhaniyaDautbekova!

I am trying to reproduce your case, but all will be OK.
* **helium-ext.scss**
  ```
  @mixin com_company_demo-helium-ext {
  /* Button */
  --button-primary-active-color: #EF7F1A;
  --button-primary-color: #EF7F1A;
  --button-primary-disabled-color: #FAC08C;
  --button-primary-disabled-text-color: #FFFFFF;
  --button-primary-focused-border-color: #EF7F1A;
  --button-primary-hover-color: #EF7F1A;
  --button-primary-text-color: #FFFFFF;
  }
  ```
* **Xml descriptor**
  ```
  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
  <window xmlns="http://schemas.haulmont.com/cuba/screen/window.xsd"
        caption="msg://newScreen.caption"
        messagesPack="com.company.demo.web.screens">
      <layout>
          <vbox spacing="true">
              <button caption="Disabled Btn" enable="false" stylename="primary"/>
              <button caption="Enable Btn" stylename="primary"/>
          </vbox>
      </layout>
  </window>
  ```
* **Result**
![image](https://user-images.githubusercontent.com/35256248/85672378-e126ea00-b6d3-11ea-8c66-dfdc54e39f4f.png)

We have a [forum](https://www.cuba-platform.com/discuss/) for such questions. Please create a topic there, it will be more convenient.
Also, please attach a screenshot from the devTools browser, where the style applied to the  disabled button will be visible.
Example:
![image](https://user-images.githubusercontent.com/35256248/85673267-c739d700-b6d4-11ea-886f-c59b51f9fa7b.png)

Regards,
Gleb

**Comment by ZhaniyaDautbekova** [comment]
can you check also for action button?
![image](https://user-images.githubusercontent.com/67406294/85688976-0deaf980-b6f4-11ea-9faa-dabb676c3352.png)

**Comment by web-devel** [comment]
Hi @ZhaniyaDautbekova , thanks for the feedback. I've already created an [issue](https://github.com/cuba-platform/helium-theme/issues/36) in `helium-theme` repository.
